project:
  type: website

website:
  title: "Education in Florida"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tampa.qmd
        text: Tampa
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    